### PR TITLE
Professor Form for small screens

### PR DESCRIPTION
**Pull request by TrueshotBarrage**
Not sure why it can't auto merge lol. I only updated media queries as far as I am concerned... 

Screen Shot 2020-11-09 at 8 24 02 PM

### CODE REVIEW

**Comment by oscarso2000** [comment]
ill resolve the conflicts later dont worry. u just fixed the CSS right? @TrueshotBarrage

**Comment by TrueshotBarrage** [comment]
I resolved the merge conflicts, please feel free to merge them after review

**Comment by oscarso2000** [comment]
you've reverted back some of the changes on the files when fixing the merge conflicts.

**Comment by oscarso2000** [comment]
dont worry about it. i have done what u did in #173

**Pull request closed without merging**
