### PR TITLE
[UI/UX] Professor form updates & signup data changes

### PR DESCRIPTION
**Pull request by TrueshotBarrage**
- Prof form UI updates. Uses CSS grid
- TODO: media queries for smaller screens
- signup_data.py might be merge blocked with branch "oscar" due to overlapping (same) code

### CODE REVIEW

**Review by oscarso2000 — COMMENTED** [review]
Good. Need to fix S3 python code where it keeps jumping into the except statement because somehow boto3 doesn't recognize we have a file there. And also need to work on recognizing professor for signup instead of having the abouts page link to the signup. page.

**Comment by oscarso2000** [comment]
I have removed my PR too. Make sure you git pull before continuing to work on the issues above.

**Comment by oscarso2000** [comment]
Can you also post some screenshots of what it looks like now?

**Review by oscarso2000 — COMMENTED** [review]
fixed s3 bug

**Comment by TrueshotBarrage** [comment]
Sure, here they are:

Screen Shot 2020-10-29 at 9 31 12 AM

Screen Shot 2020-10-29 at 9 31 36 AM

As you can see, we need media queries for small screens asap. I tried to get some to work but for some reason they weren't working like I expected them to. If anyone else wants to try, go right ahead.

Also, form validation should be looser than it currently is (especially for the links). We should do some of the dirty work of parsing the URL instead of making the user go through the hassle of pasting the link exactly in the format we need it (for instance, having the ?post=asdf stuff within the URL -- easy fix on our end). If not, then we should at least have better error messages. It might be very confusing for the prof to find out on their own atm. Took me a few tries personally to get everything right.

**Comment by TrueshotBarrage** [comment]
I also feel that we could make the site look a bit more aesthetically pleasing. But I'm not sure how exactly lol. Maybe a different color scheme? Any ideas

**Comment by oscarso2000** [comment]
Merged in #168

**Comment by TrueshotBarrage** [comment]
@oscarso2000 @bayoumi17m @shljessie would love your input on the comments above regarding form validation and making the website look nicer

**Pull request closed without merging**
