### PR TITLE
[UX/UI]Card Display and Search Screen Spacing Changes

### PR DESCRIPTION
**Pull request by shljessie**
These are small changes made in the Search Screen Page and the Card Display Spacing. I was going to make bigger ux changes along with these small ones but its taking a while so I'm pushing these ones first

### Search Screen
The search bar was placed top, left 50% but because of the top navigation bar, it looked slightly low on the screen. I pulled it up.

**After**
Screen Shot 2020-09-28 at 10 11 32 PM

### Card Result Display

**Previous**
The space between the card displays and the result were a bit awkward so I  evenly spaced out the cards and the result display
Screen Shot 2020-09-28 at 10 12 14 PM

**After**
Screen Shot 2020-09-28 at 10 15 22 PM

### Text Align
**Previous**
The wasn't aligned properly so I made those changes
Screen Shot 2020-09-28 at 10 16 36 PM

**After**
Screen Shot 2020-09-28 at 10 17 18 PM

### CODE REVIEW

**Comment by bayoumi17m** [comment]
This PR seems to include changes from #148, is this intended? If so, the corresponding changes at least need to be made here.

**Comment by oscarso2000** [comment]
Nice! Please read what Magd has written. @bayoumi17m , if we merge #148 first after it's all fixed up and then this one, i think the files shouldn't be too different?

**Comment by bayoumi17m** [comment]
Yep, but it's also about just being able to evaluate the changes specified in this PR not both combined. My suggestion would be to fix the `shljessie:master` then merge those changes into `shljessie:spacing-changes` before re-evaluating this PR.

**Comment by TrueshotBarrage** [comment]
The code looks good to me

**Review by TrueshotBarrage — APPROVED** [review]

**Comment by shljessie** [comment]
I deleted all the uncesscessary files DS_store, yarn.lock, and vscode/launch.json files and also changed encorewebsm --> encoreweblg should I remove the overlapping changes with my previous file too? @bayoumi17m

**Review by oscarso2000 — APPROVED** [review]
Looks good. Waiting on Magd's review.

**Comment by oscarso2000** [comment]
I don't think there'd be any merge conflicts but just make sure you're always working with the most up to date branch :)

**Review by bayoumi17m — APPROVED** [review]

**Comment by bayoumi17m** [comment]
Merge monday!

**Pull request merged**
